"""initial schema

Revision ID: 35213c5faf06
Revises: 
Create Date: 2026-05-24 01:44:19.553934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35213c5faf06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.TEXT(), server_default=sa.text("'''[]''::text'::text"), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
