"""drop legacy samples.tags column

Historically this was the base revision, but it created no tables. The real
base is now a1b2c3d4e5f6; this revision keeps only the column drop it actually
performed.

Revision ID: 35213c5faf06
Revises: a1b2c3d4e5f6
Create Date: 2026-05-24 01:44:19.553934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35213c5faf06'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    columns = {column['name'] for column in sa.inspect(op.get_bind()).get_columns('samples')}
    if 'tags' not in columns:
        # Already absent on databases built from the current models.
        return
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_column('tags')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.TEXT(), server_default=sa.text("'''[]''::text'::text"), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
