"""create base schema

This is the real starting point of the migration history. The revision that
used to be the base ("initial schema", 35213c5faf06) was autogenerated against
an already-populated database, so it only dropped a column and created no
tables at all -- which meant `flask db upgrade` could never build a fresh
database from scratch.

Tables are created here in their *historical* shape (samples still has `tags`,
community_posts has no moderation columns) so that the later revisions, which
alter them, still apply cleanly on top.

Each create is skipped when the table already exists, so this is also safe to
run against a database that was previously built with `db.create_all()` and
never stamped.

Revision ID: a1b2c3d4e5f6
Revises:
Create Date: 2026-09-10 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


revision = 'a1b2c3d4e5f6'
down_revision = None
branch_labels = None
depends_on = None


def _existing_tables():
    return set(sa.inspect(op.get_bind()).get_table_names())


def upgrade():
    existing = _existing_tables()

    if 'users' not in existing:
        op.create_table(
            'users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('username', sa.String(length=50), nullable=False),
            sa.Column('password_hash', sa.String(length=255), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('class_name', sa.String(length=100), nullable=True),
            sa.Column('school', sa.String(length=255), nullable=True),
            sa.Column('cohort', sa.String(length=100), nullable=True),
            sa.Column('role', sa.String(length=50), nullable=True),
            sa.Column('bio', sa.Text(), nullable=True),
            sa.Column('avatar', sa.Text(), nullable=True),
            sa.Column('stats', sa.JSON(), nullable=False),
            sa.Column('progress', sa.JSON(), nullable=False),
            sa.Column('commit_weeks', sa.JSON(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
        )
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
            batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    if 'user_practice_sessions' not in existing:
        op.create_table(
            'user_practice_sessions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('topic', sa.String(length=500), nullable=False),
            sa.Column('transcript', sa.Text(), nullable=False),
            sa.Column('duration', sa.Float(), nullable=False),
            sa.Column('scores', sa.JSON(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
        )
        with op.batch_alter_table('user_practice_sessions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_user_practice_sessions_user_id'), ['user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_user_practice_sessions_created_at'), ['created_at'], unique=False)

    if 'community_posts' not in existing:
        # Moderation columns are added by revision 5f2f9d6f4d58.
        op.create_table(
            'community_posts',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=180), nullable=False),
            sa.Column('body', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
        )
        with op.batch_alter_table('community_posts', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_community_posts_user_id'), ['user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_community_posts_created_at'), ['created_at'], unique=False)

    if 'app_announcements' not in existing:
        op.create_table(
            'app_announcements',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('enabled', sa.Boolean(), nullable=False),
            sa.Column('message', sa.Text(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
        )

    if 'analysis_jobs' not in existing:
        op.create_table(
            'analysis_jobs',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('topic', sa.Text(), nullable=False),
            sa.Column('source', sa.String(length=50), nullable=False),
            sa.Column('original_filename', sa.String(length=500), nullable=False),
            sa.Column('stored_audio_path', sa.String(length=1000), nullable=False),
            sa.Column('status', sa.String(length=32), nullable=False),
            sa.Column('progress_message', sa.String(length=255), nullable=False),
            sa.Column('error_message', sa.Text(), nullable=True),
            sa.Column('result_payload', sa.JSON(), nullable=True),
            sa.Column('document_path', sa.String(length=1000), nullable=True),
            sa.Column('started_at', sa.DateTime(), nullable=True),
            sa.Column('completed_at', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
            sa.PrimaryKeyConstraint('id'),
        )
        with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_analysis_jobs_user_id'), ['user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_analysis_jobs_status'), ['status'], unique=False)
            batch_op.create_index(batch_op.f('ix_analysis_jobs_created_at'), ['created_at'], unique=False)

    if 'rate_limit_entries' not in existing:
        op.create_table(
            'rate_limit_entries',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('scope', sa.String(length=100), nullable=False),
            sa.Column('identifier', sa.String(length=255), nullable=False),
            sa.Column('window_key', sa.BigInteger(), nullable=False),
            sa.Column('count', sa.Integer(), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('scope', 'identifier', 'window_key', name='uq_rate_limit_scope_identifier_window'),
        )
        with op.batch_alter_table('rate_limit_entries', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_rate_limit_entries_scope'), ['scope'], unique=False)
            batch_op.create_index(batch_op.f('ix_rate_limit_entries_identifier'), ['identifier'], unique=False)
            batch_op.create_index(batch_op.f('ix_rate_limit_entries_window_key'), ['window_key'], unique=False)
            batch_op.create_index(batch_op.f('ix_rate_limit_entries_expires_at'), ['expires_at'], unique=False)

    if 'questions' not in existing:
        op.create_table(
            'questions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('topic', sa.String(length=500), nullable=False),
            sa.Column('question', sa.Text(), nullable=False),
            sa.Column('category', sa.String(length=200), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
        )

    if 'samples' not in existing:
        # `tags` is dropped by revision 35213c5faf06; it is created here so that
        # revision still has something to drop on a fresh database.
        op.create_table(
            'samples',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('filename', sa.String(length=500), nullable=False),
            sa.Column('topic', sa.String(length=500), nullable=False),
            sa.Column('question', sa.Text(), nullable=True),
            sa.Column('speaker', sa.String(length=200), nullable=False),
            sa.Column('score', sa.Float(), nullable=False),
            sa.Column('duration', sa.Integer(), nullable=True),
            sa.Column('transcript', sa.Text(), nullable=False),
            sa.Column('feedback', sa.Text(), nullable=False),
            sa.Column('audio_url', sa.String(length=1000), nullable=True),
            sa.Column('tags', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
        )


def downgrade():
    for table in (
        'samples',
        'questions',
        'rate_limit_entries',
        'analysis_jobs',
        'app_announcements',
        'community_posts',
        'user_practice_sessions',
        'users',
    ):
        op.drop_table(table)
